% CoaXial Force and Moment Equation (refactored: params struct p instead of globals)

function [Force, Moment] = CoaX_Dyn(Omega_up, Omega_dw, alpha, beta, p)

T_up = p.c_T(1) * pi * p.rho * p.D^4 * Omega_up^2;
T_dw = p.c_T(2) * pi * p.rho * p.D^4 * Omega_dw^2;
Q_up = p.c_Q(1) * pi * p.rho * p.D^5 * Omega_up^2;
Q_dw = p.c_Q(2) * pi * p.rho * p.D^5 * Omega_dw^2;

Thrust_dw = eul2rotm([0, beta, alpha]) * [0; 0; -T_dw];  % Thrust considering tilt angle in body fixed frame
Thrust_up = [0; 0; -T_up];                                 % Thrust generated by upper rotor in body fixed frame

Force = Thrust_dw + Thrust_up;                              % Total Thrust generated by rotors

Moment(1,:) = p.r_cd * T_dw * sin(alpha);                  % CoaXial Moment
Moment(2,:) = p.r_cd * T_dw * cos(alpha) * sin(beta);
Moment(3,:) = Q_up - Q_dw;

end
